---
- name: Upgrade the system
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- import_tasks: user_setup.yml

- import_tasks: install_apt_packages.yml

- import_tasks: install_npm_clis.yml

- name: Check previous installation
  stat:
    path: "{{ ghost_install_dir }}/current/index.js"
  register: ghost_is_installed

- import_tasks: setup_ghost_db.yml

- import_tasks: run_ghost_setup.yml
  when: "not ghost_is_installed.stat.exists"
