---
- name: Create web folder with correct permissions
  become: true
  file:
    path: "{{ ghost_install_dir }}"
    state: directory
    mode: "0777"
    owner: ghost
    recurse: true

- name: Install ghost using ghost-cli
  become: true
  become_user: "{{ ghost_user_name }}"
  shell: "ghost install --url={{ ghost_url }} --db={{ ghost_db }} --dbhost={{ ghost_db_host }} --dbuser={{ ghost_db_user }} --dbpass={{ ghost_db_password }} --dbname={{ ghost_db_name }} --sslemail={{ ghost_letsencrypt_user }} --no-setup-ssl --no-prompt --start"
  args:
    chdir: "{{ ghost_install_dir }}"

- name: Install SSL for ghost using let's encrypt
  shell: "ghost config url {{ ghost_project_url_secure }} && ghost setup ssl --sslemail={{ ghost_letsencrypt_user }} --no-prompt"
  args:
    chdir: "{{ ghost_install_dir }}"
