---
- name: Create MySQL ghost database
  mysql_db:
    name: "{{ ghost_db_name }}"
    state: present

- name: Create MySQL users for ghost
  mysql_user:
    name: "{{ ghost_db_user }}"
    password: "{{ ghost_db_password }}"
    host: "{{ ghost_db_host }}"
    login_host: "{{ ghost_db_host }}"
    priv: "{{ ghost_db_name }}.*:ALL"
    state: present